package commands

import (
	"encoding/json"
	"sort"
	"strings"
)

// Per-host renderers turn the read/write/destructive classification into safety config. This is
// a READ-FIRST CLI: the destructive bucket carries `messages send` (the one write — irreversible
// and the classic account-restriction trigger), and the guard's job is to (a) hard-block it plus
// anything a future release adds as a write/destructive command, and (b) deny `linkedin alias
// set`, which could mint a shorthand for a blocked command. Each renderer emits both binary
// (Bash) patterns and MCP tool patterns so an agent driving linkedin either way hits the same
// rails.

// claudeSettingsJSON builds the settings.json permission fragment: deny irreversible (canonical
// + alias paths + `alias set`), ask writes, allow reads. These are literal prefix rules — the
// hook is the enforcement layer (§3b hardening #1).
func claudeSettingsJSON(c classification) (string, error) {
	deny := make([]string, 0)
	ask := make([]string, 0)
	allow := make([]string, 0)
	for _, cmd := range c.Destructive {
		for _, p := range cmd.AllPaths() {
			deny = append(deny, bashPattern(p))
		}
		deny = append(deny, mcpToolPattern(cmd.Path))
	}
	// `linkedin alias set` can mint a shorthand that expands to a (future) blocked command before
	// cobra parses it — deny creating new indirections.
	deny = append(deny, bashPattern("alias set"))
	for _, cmd := range c.Write {
		for _, p := range cmd.AllPaths() {
			ask = append(ask, bashPattern(p))
		}
		ask = append(ask, mcpToolPattern(cmd.Path))
	}
	for _, cmd := range c.Read {
		for _, p := range cmd.AllPaths() {
			allow = append(allow, bashPattern(p))
		}
		allow = append(allow, mcpToolPattern(cmd.Path))
	}

	// ${CLAUDE_PROJECT_DIR} is the Claude runtime variable; Claude substitutes it when loading
	// the hook — it is NOT expanded here.
	hookPath := "${CLAUDE_PROJECT_DIR}/.claude/hooks/linkedin-guard.sh"
	hookEntry := func(matcher string) map[string]any {
		return map[string]any{
			"matcher": matcher,
			"hooks":   []any{map[string]any{"type": "command", "command": hookPath}},
		}
	}
	settings := map[string]any{
		"permissions": map[string]any{
			"deny":  deny,
			"ask":   ask,
			"allow": allow,
		},
		"hooks": map[string]any{
			"PreToolUse": []any{hookEntry("Bash"), hookEntry("mcp__linkedin__")},
		},
		"_comment": "Generated by `linkedin agent guard --host claude-code`. Save the hook script to " +
			".claude/hooks/linkedin-guard.sh (chmod +x) and merge this fragment into .claude/settings.json. " +
			"linkedin is read-first: deny = irreversible operations (messages send) incl. alias paths and " +
			"`alias set`; ask = future writes; allow = reads. MCP-only operation is the hard guarantee.",
	}
	b, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return "", err
	}
	return string(b) + "\n", nil
}

// renderClaudeCode emits the hook script and the settings fragment as one reviewable document
// (use --write to materialize the files instead).
func renderClaudeCode(c classification) (string, error) {
	settings, err := claudeSettingsJSON(c)
	if err != nil {
		return "", err
	}
	var out strings.Builder
	out.WriteString("# ----- .claude/hooks/linkedin-guard.sh (save + chmod +x) -----\n")
	out.WriteString(hookScript(c))
	out.WriteString("\n# ----- merge into .claude/settings.json -----\n")
	out.WriteString(settings)
	return out.String(), nil
}

// hookScript generates the PreToolUse hook. Blocked commands are matched by exact SUBCOMMAND
// PATH at the command position — never by bare verbs anywhere in the line — with an optional
// path prefix before the binary so ./bin/linkedin and /usr/local/bin/linkedin are caught too.
func hookScript(c classification) string {
	seenCLI := map[string]bool{}
	seenTool := map[string]bool{}
	var cliPaths, toolNames []string
	for _, cmd := range c.Destructive {
		for _, p := range cmd.AllPaths() {
			if !seenCLI[p] {
				seenCLI[p] = true
				cliPaths = append(cliPaths, p)
			}
		}
		if t := mcpToolPattern(cmd.Path); !seenTool[t] {
			seenTool[t] = true
			toolNames = append(toolNames, t)
		}
	}
	// `alias set` can rewrite a future invocation into a blocked command before cobra parses it.
	if !seenCLI["alias set"] {
		cliPaths = append(cliPaths, "alias set")
	}
	sort.Strings(cliPaths)
	sort.Strings(toolNames)

	var cliArray strings.Builder
	cliArray.WriteString("blocked_cmds=(\n")
	for _, p := range cliPaths {
		safe := strings.ReplaceAll(p, "'", "'\\''")
		cliArray.WriteString("  '" + safe + "'\n")
	}
	cliArray.WriteString(")")

	var toolArray strings.Builder
	toolArray.WriteString("blocked_tools=(\n")
	for _, t := range toolNames {
		safe := strings.ReplaceAll(t, "'", "'\\''")
		toolArray.WriteString("  '" + safe + "'\n")
	}
	toolArray.WriteString(")")

	return `#!/usr/bin/env bash
# linkedin agent guard — blocks irreversible linkedin operations on the Bash and MCP
# surfaces. linkedin is READ-FIRST: today ` + "`messages send`" + ` (irreversible, the classic
# account-restriction trigger) and ` + "`alias set`" + ` are blocked; any future write/destructive
# command appears here automatically.
# Generated by ` + "`linkedin agent guard`" + `; regenerate after upgrading linkedin.
#
# MATCHING STRATEGY: commands are matched by exact SUBCOMMAND PATH at the command position,
# not by bare verbs anywhere in the line. For each blocked cli-path P we check whether the
# CLEANED command string matches the anchored ERE:
#   (^|[;&|([:space:]]+)([^[:space:]]*/)?linkedin[[:space:]]+<P>([[:space:];&|)]|$)
# The optional ([^[:space:]]*/)? prefix catches ./bin/linkedin and /usr/local/bin/linkedin,
# while a different binary that merely ends in "linkedin" (mylinkedin) is NOT matched. The
# trailing class also covers a separator glued to the verb (P;true).
#
# De-obfuscation: quotes (\042 / \047) and backslash (\134) are stripped before matching to
# defeat de""lete-style tricks. Variable indirection and shell aliases are NOT defeated — use
# MCP-only mode or a read-only sandbox for a hard guarantee.

# --- blocked command paths (Bash surface; canonical + cobra alias paths) ---
` + cliArray.String() + `

# --- blocked MCP tool names (exact) ---
` + toolArray.String() + `

input=$(cat)

# deny_raw emits a denial with a FIXED reason via printf (no jq needed).
deny_raw() {
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"%s"}}\n' "$1"
  exit 0
}

# deobfuscate strips quote chars (\042=", \047=', \134=\) and collapses newlines so tricks
# can't split a token across lines. Applied in BOTH the jq and no-jq branches.
deobfuscate() {
  printf '%s' "$1" | tr -d '\042\047\134' | tr '\n' ' '
}

# bash_is_blocked returns 0 (true) if the cleaned command contains a blocked linkedin
# subcommand path at the command position.
bash_is_blocked() {
  local cleaned="$1"
  local p
  for p in "${blocked_cmds[@]}"; do
    local pat
    pat=$(printf '%s' "$p" | sed 's/ /[[:space:]]+/g')
    if printf '%s' "$cleaned" | grep -qiE "(^|[;&|([:space:]]+)([^[:space:]]*/)?linkedin[[:space:]]+${pat}([[:space:];&|)]|\$)"; then
      return 0
    fi
  done
  return 1
}

# Without jq we cannot isolate the tool_name/command fields. Fail safe: apply the same
# de-obfuscation and anchored path matching on the raw payload. Flatten JSON structure chars
# too, or the payload reads {command:linkedin ...} and the anchor never matches (fail-open).
if ! command -v jq >/dev/null 2>&1; then
  flat=$(printf '%s' "$input" | tr '\n{}:,' '     ')
  cleaned=$(deobfuscate "$flat")
  if bash_is_blocked "$cleaned"; then
    deny_raw "linkedin agent guard: irreversible operation blocked (jq unavailable; raw match)."
  fi
  exit 0
fi

# deny emits the denial with a jq-escaped reason.
deny() {
  jq -c -n --arg r "$1" \
    '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:$r}}'
  exit 0
}

tool=$(printf '%s' "$input" | jq -r '.tool_name // empty')
case "$tool" in
  Bash)
    raw_cmd=$(printf '%s' "$input" | jq -r '.tool_input.command // empty')
    cleaned=$(deobfuscate "$raw_cmd")
    if bash_is_blocked "$cleaned"; then
      deny "linkedin agent guard: irreversible operation blocked."
    fi
    ;;
  *)
    # MCP branch: exact set-membership — no substring or regex match.
    for t in "${blocked_tools[@]}"; do
      if [ "$tool" = "$t" ]; then
        deny "linkedin agent guard: irreversible MCP tool blocked (${tool})."
      fi
    done
    ;;
esac
exit 0
`
}

// renderCodex emits a Codex config.toml: a read-only sandbox with approvals required, plus a
// commented list of the irreversible commands a reviewer should never auto-approve. Codex reads
// TOP-LEVEL sandbox_mode/approval_policy keys (§3b hardening #8).
func renderCodex(c classification) (string, error) {
	var b strings.Builder
	b.WriteString("# Generated by `linkedin agent guard --host codex`.\n")
	b.WriteString("# Read-only sandbox: linkedin is read-first; reads run freely, sends need approval.\n")
	b.WriteString("approval_policy = \"on-request\"\n")
	b.WriteString("sandbox_mode = \"read-only\"\n\n")
	if len(c.Destructive) > 0 {
		b.WriteString("# Never auto-approve these irreversible linkedin operations (nor their cobra alias paths):\n")
		for _, cmd := range c.Destructive {
			b.WriteString("#   linkedin " + cmd.Path + "\n")
		}
	} else {
		b.WriteString("# linkedin has no irreversible operations today (read-only client).\n")
	}
	b.WriteString("# `linkedin alias set` can mint a shorthand for a future blocked command — never\n")
	b.WriteString("# auto-approve it.\n")
	if len(c.Write) > 0 {
		b.WriteString("\n# These writes should require approval:\n")
		for _, cmd := range c.Write {
			b.WriteString("#   linkedin " + cmd.Path + "\n")
		}
	}
	return b.String(), nil
}

// renderOpenCode emits an opencode.json permission map: deny destructive (canonical and alias
// paths, plus `alias set`), ask writes, allow reads — keyed by the Bash command patterns
// OpenCode matches. `permission` is singular with a bash sub-map (§3b hardening #8).
func renderOpenCode(c classification) (string, error) {
	perms := map[string]string{}
	for _, cmd := range c.Destructive {
		for _, p := range cmd.AllPaths() {
			perms["linkedin "+p+"*"] = "deny"
		}
	}
	perms["linkedin alias set*"] = "deny"
	for _, cmd := range c.Write {
		for _, p := range cmd.AllPaths() {
			perms["linkedin "+p+"*"] = "ask"
		}
	}
	for _, cmd := range c.Read {
		for _, p := range cmd.AllPaths() {
			perms["linkedin "+p+"*"] = "allow"
		}
	}
	root := map[string]any{
		"$schema": "https://opencode.ai/config.json",
		"permission": map[string]any{
			"bash": perms,
		},
		"_comment": "Generated by `linkedin agent guard --host opencode`. Merge into opencode.json. " +
			"linkedin is read-only: deny covers future irreversible ops (with alias paths) and `alias set`; " +
			"these are literal prefix rules — for obfuscation-resistant blocking use --host claude-code (hook) " +
			"or MCP-only mode.",
	}
	b, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return "", err
	}
	return string(b) + "\n", nil
}
